### ISSUE TITLE
MFCC generation script missing.

### ISSUE THREAD

**Issue by imrnh** [0xSameer/ast#1]
`!python beam.py -m experiments/es_en_20h -n 5 -k 5 -w 0.6 -s fisher_dev`

Generated the following error:

Beam for: experiments/es_en_20h gpu: 0
--------------------------------------------------------------------------------
Computing beam results
  0%|                                                  | 0/3977 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/beam.py", line 111, in <module>
    for utt in nn.data_loader.get_batch(1,
  File "/content/dataloader.py", line 145, in get_batch
    batch_data["X"].append(self._load_speech(u, set_key, max_sp))
  File "/content/dataloader.py", line 103, in _load_speech
    x_data = xp.load(utt_path)[:max_sp]
  File "/usr/local/lib/python3.10/dist-packages/cupy/_io/npz.py", line 64, in load
    obj = numpy.load(file, mmap_mode, allow_pickle)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../speech2text/mfcc_13dim/fisher_dev/20051009/20051009_182032_217_fsp-B-100.npy'

The documentation (.md and .pdf) doesn't seem consistent for creating .npy files. Most of the shell command either missing or path not included correctly. Any fix possible?

Using cuda12.2:
`nvcc --version` output:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

**Comment by imrnh** [comment]
If possible, can you provide the following files ?

**Comment by imrnh** [comment]
@0xSameer is there any way I can get those  .npy files needed to run the code?
